name: Build RedProcessor App

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build RedProcessor app
        run: |
          npx electron-packager . RedProcessor --platform=linux --arch=x64 --out=dist/
          npx electron-packager . RedProcessor --platform=win32 --arch=x64 --out=dist/
          npx electron-packager . RedProcessor --platform=darwin --arch=x64 --out=dist/
